"""AdmissionCheck upgrade test constants."""

AC_NAMESPACE = "upgrade-admission-check"
AC_ADMISSION_CHECK_NAME = "upgrade-test-ac"
AC_CONTROLLER_NAME = "upgrade-test-controller.example.com"
AC_RESOURCE_FLAVOR = "ac-upgrade-flavor"
AC_CLUSTER_QUEUE = "ac-upgrade-cq"
AC_LOCAL_QUEUE = "ac-upgrade-lq"
AC_CPU_QUOTA = 4
AC_MEMORY_QUOTA = "8Gi"
AC_JOB_NAME = "ac-upgrade-job"
AC_JOB_CPU_REQUEST = "100m"
AC_JOB_MEMORY_REQUEST = "64Mi"
AC_JOB_CPU_LIMIT = "200m"
AC_JOB_MEMORY_LIMIT = "256Mi"
AC_BASELINE_CM = "upgrade-ac-baseline"
