"""Constants for MaaS ai-gateway-controller component health tests."""

AI_GATEWAY_CONTROLLER_DEPLOYMENT_NAME: str = "ai-gateway-controller"
AI_GATEWAY_CONTROLLER_MANAGER_CONTAINER_NAME: str = "manager"
AI_GATEWAY_CONTROLLER_SERVICE_ACCOUNT_NAME: str = "ai-gateway-controller"
AI_GATEWAY_CONTROLLER_CLUSTER_ROLE_NAME: str = "ai-gateway-controller-role"
AI_GATEWAY_CONTROLLER_CLUSTER_ROLE_BINDING_NAME: str = "ai-gateway-controller-rolebinding"
AI_GATEWAY_CONTROLLER_AITENANT_RESOURCE: str = "aitenants"
AI_GATEWAY_CONTROLLER_AITENANT_WATCH_VERBS: frozenset[str] = frozenset({"get", "list", "watch"})

AI_GATEWAY_CONTROLLER_PARAMETERS_CONFIGMAP_NAME: str = "ai-gateway-controller-parameters"
AI_GATEWAY_CONTROLLER_IMAGE_CONFIGMAP_KEY: str = "ai-gateway-controller-image"
PRAXIS_EXTPROC_IMAGE_CONFIGMAP_KEY: str = "praxis-extproc-image"

RELATED_IMAGE_ODH_PRAXIS_EXTPROC_ENV_NAME: str = "RELATED_IMAGE_ODH_PRAXIS_EXTPROC_IMAGE"

AIGATEWAY_CR_NAME: str = "default-aigateway"
MODELS_AS_A_SERVICE_READY_CONDITION: str = "ModelsAsAServiceReady"

AI_GATEWAY_CONTROLLER_DEPLOYMENT_AVAILABLE_TIMEOUT: int = 120
AIGATEWAY_CR_CONDITION_TIMEOUT: int = 300

AI_GATEWAY_CONTROLLER_HEALTH_PROBE_PORT: int = 8081
AI_GATEWAY_CONTROLLER_LIVENESS_PROBE_PATH: str = "/healthz"
AI_GATEWAY_CONTROLLER_READINESS_PROBE_PATH: str = "/readyz"
