name: Build and Push Container Image On PR Merge

on:
  pull_request_target:
    types: [closed]

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  resolve-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Set image tag
        id: tag
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: |
          if [ "$BASE_REF" == "main" ]; then
              echo "tag=latest" >> "$GITHUB_OUTPUT"
          else
              echo "tag=$BASE_REF" >> "$GITHUB_OUTPUT"
          fi

  build-push:
    needs: resolve-tag
    permissions:
      pull-requests: write
      contents: read
      issues: write
    uses: ./.github/workflows/build-push-image.yml
    with:
      ref: ${{ github.event.pull_request.base.ref }}
      tag: ${{ needs.resolve-tag.outputs.tag }}
      comments_url: ${{ github.event.pull_request.comments_url }}
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }} # pragma: allowlist secret
